source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Chirp_Example', :exclusive => true do
  pod "Chirp", :path => "../"
end

target 'Chirp_Tests', :exclusive => true do
  pod "Chirp", :path => "../"

  pod 'Quick'
  pod 'Nimble'
end
